exec2: exec_cat exec_wc exec_grep exec2.c
	gcc -o exec2 exec2.c

exec_cat: exec_cat.c
	gcc -o exec_cat exec_cat.c

exec_wc: exec_wc.c
	gcc -o exec_wc exec_wc.c

exec_grep: exec_grep.c
	gcc -o exec_grep exec_grep.c


exec_redirect: exec_wc exec_redirect.c
	gcc -o exec_redirect exec_redirect.c
