exec2: exec_cat exec_wc exec_grep exec2.c
	gcc -o exec2 exec2.c

exec_cat: exec_cat.c
	gcc -o exec_cat exec_cat.c

exec_wc: exec_wc.c
	gcc -o exec_wc exec_wc.c

exec_grep: exec_grep.c
	gcc -o exec_grep exec_grep.c


exec_redirect: exec_wc exec_redirect.c
	gcc -o exec_redirect exec_redirect.c

q1: q1.c
	gcc -o q1 q1.c

q2: q2.c
	gcc -o q2 q2.c

q3: q3.c
	gcc -o q3 q3.c

q4: q4.c
	gcc -o q4 q4.c

q5: q5.c
	gcc -o q5 q5.c

q6: q6.c
	gcc -o q6 q6.c

q7: q7.c
	gcc -o q7 q7.c

q8: q8.c
	gcc -o q8 q8.c
